#!/usr/bin/env node
// tools/genfont.mjs — convert font8x8_basic.h to src/tables/font8x8.ts
// Run: node tools/genfont.mjs /tmp/f8.h
import { readFileSync, writeFileSync } from 'node:fs';

const src = readFileSync(process.argv[2] || '/tmp/f8.h', 'utf8');
const bytes = [];
for (const m of src.matchAll(/0x([0-9a-fA-F]{2})/g)) bytes.push(parseInt(m[1], 16));
// The table is the FULL ASCII range: index = code * 8 (glyph 0 first).
if (bytes.length < 1024) throw new Error('expected 1024 glyph rows, got ' + bytes.length);
bytes.length = 1024; // drop any hexes picked up from comments

// index 0 => ASCII code. Extract printable ASCII 32..126 => 95 glyphs
const glyphs = {};
for (let code = 32; code < 127; code++) {
  const rows = [];
  for (let r = 0; r < 8; r++) {
    const b = bytes[code * 8 + r];
    let s = '';
    for (let c = 0; c < 8; c++) s += (b >> c) & 1 ? '1' : '.'; // bit0 = leftmost pixel
    rows.push(s);
  }
  glyphs[String.fromCharCode(code)] = rows;
}

function esc(ch) {
  if (ch === "'") return "\\'";
  if (ch === '\\') return '\\\\';
  return ch;
}
let out = '// GENERATED by tools/genfont.mjs from font8x8_basic.h (public domain, Daniel Hepper).\n';
out += '// 8x8 glyphs, ASCII 32..126. Bit 0 of each byte is the LEFTMOST pixel.\n';
out += "export const FONT8X8: Record<string, string[]> = {\n";
for (const ch of Object.keys(glyphs)) {
  out += `  '${esc(ch)}': [\n`;
  out += glyphs[ch].map((r) => `    '${r}',`).join('\n');
  out += '\n  ],\n';
}
out += '};\n';
writeFileSync(new URL('../src/tables/font8x8.ts', import.meta.url), out);
console.log('wrote src/tables/font8x8.ts,', Object.keys(glyphs).length, 'glyphs');
